Feature/connect mentions
attech-org/leleka pull request #112
Opened 2022-09-20 15:17 UTC by ArtemLigerko

![WM-Screenshots-20220920181709](https://user-images.githubusercontent.com/103952847/191297548-6a69a61b-67ec-485b-acc2-c709a271fd77.png)

2022-09-21 14:10 UTC, KirillSerg approved these changes
Goog

2022-09-21 16:21 UTC, DavidKorystov approved these changes
lgtm

2022-09-21 16:21 UTC, DavidKorystov commented on src/containers/MentionsList.tsx
> +        mentions.docs.length || null ? (
I'm not sure.
```suggestion
        mentions.docs.length ? (
```

2022-09-21 18:45 UTC, VitaliiDenysyuk requested changes

2022-09-21 18:45 UTC, VitaliiDenysyuk commented on src/containers/MentionsList.tsx
> +    );
```suggestion
    dispatch(
      tweetsActions.fetchMentions({
        limit: mentions.limit,
        nextPage: mentions.nextPage,
        searchString: `@${user.username}`,
      })
    );
```
you use this block two times. create arrow function and call it.

2022-09-21 18:45 UTC, VitaliiDenysyuk commented on src/containers/MentionsList.tsx
> +      !mentions.isLoading &&
```suggestion
      !mentions.isLoading &&
      mentions.hasNextPage &&
```
if there is not  next page we don't load it

2022-09-22 18:40 UTC, AndrewKaenko approved these changes
Lgtm!

2022-09-22 18:45 UTC, alexandrtovmach approved these changes

2022-09-22 18:45 UTC, merged