Feature/make login and register forms consistent
attech-org/leleka pull request #114
Opened 2022-09-21 11:29 UTC by Tretmax

![image](https://user-images.githubusercontent.com/103947044/191491959-569fe879-1036-4a10-89b0-dd9a9d7e79a8.png)

![image](https://user-images.githubusercontent.com/103947044/191492726-ae618bfe-f3ed-4878-af6f-ec851f2abde5.png)

2022-09-21 15:30 UTC, ArtemLigerko commented on src/containers/LoginForm.tsx
> +          {t("login.loginTitle")}
Change title from Twitter to Leleka

2022-09-21 15:46 UTC, DavidKorystov requested changes

2022-09-21 15:46 UTC, DavidKorystov commented on src/containers/LoginForm.tsx
>  const StyledContainer = styled(Container)`
remove this styledConteiner, use default Container

2022-09-21 15:49 UTC, DavidKorystov requested changes
Add validation to the password field and error display in the login component

2022-09-21 18:24 UTC, VitaliiDenysyuk requested changes

2022-09-21 18:24 UTC, VitaliiDenysyuk commented on src/containers/Registration.tsx
> +            placeholder="Ім'я"
use i18n

2022-09-21 18:24 UTC, VitaliiDenysyuk commented on src/containers/Registration.tsx
> +            placeholder="Ел. пошта"
use i18n

2022-09-21 18:24 UTC, VitaliiDenysyuk commented on src/containers/Registration.tsx
> +            placeholder="Пароль"
use i18n

2022-09-21 18:24 UTC, VitaliiDenysyuk commented on src/containers/Registration.tsx
> +            placeholder="Підтвердіть пароль"
use i18n

2022-09-22 06:04 UTC, VitaliiDenysyuk requested changes

2022-09-22 06:04 UTC, VitaliiDenysiuk commented on src/containers/LoginForm.tsx
> +  // Toast,
```suggestion

```
remove that

2022-09-22 06:04 UTC, VitaliiDenysiuk commented on src/containers/LoginForm.tsx
> +              placeholder="Password"
use i18n

2022-09-22 06:04 UTC, VitaliiDenysiuk commented on src/containers/LoginForm.tsx
>            </div>
<Link className="ms-1 text-decoration-none" to="/SignUpModal">
              {t("login.signUp")}
            </Link>
Link did not work
![image](https://user-images.githubusercontent.com/103836064/191670285-20c3de78-38ea-482d-9551-33d590c5af90.png)

2022-09-22 06:04 UTC, VitaliiDenysyuk commented on src/containers/Registration.tsx
> +            name="dateOfBirth"
at english have Ukrainian placeholder 
![image](https://user-images.githubusercontent.com/103836064/191669747-abec7c8d-c71c-4dbe-b1ce-7644a4774806.png)

2022-09-22 13:27 UTC, DavidKorystov commented on src/containers/LoginForm.tsx
>            </div>
use another link 
![image](https://user-images.githubusercontent.com/94183891/191759583-79709775-4d96-4c95-9a5a-f66654fb4abf.png)

2022-09-22 13:38 UTC, DavidKorystov requested changes

2022-09-22 13:38 UTC, DavidKorystov commented on src/containers/Registration.tsx
> +        </p>
Use ternary operators in the error display.
Add i18 to the registration shema, like the login shema.
```suggestion
         {errors.username && (
          <p className="text-danger fst-italic fs-6 mt-1">
            {errors?.username?.message}
          </p>
        )}
```

2022-09-22 13:38 UTC, DavidKorystov commented on src/containers/Registration.tsx
> +        </p>
Use ternary operators in the error display.
Add i18 to the registration shema, like the login shema.

2022-09-22 13:38 UTC, DavidKorystov commented on src/containers/Registration.tsx
> +        </p>
Use ternary operators in the error display.
Add i18 to the registration shema, like the login shema.

2022-09-22 13:38 UTC, DavidKorystov commented on src/containers/Registration.tsx
> +        </p>
Use ternary operators in the error display.
Add i18 to the registration shema, like the login shema.

2022-09-22 13:38 UTC, DavidKorystov commented on src/containers/Registration.tsx
> +        </p>
Use ternary operators in the error display.
Add i18 to the registration shema, like the login shema.

2022-09-22 23:37 UTC, Mykyta-Pysarev requested changes

2022-09-22 23:37 UTC, Mykyta-Pysarev commented on src/containers/LoginForm.tsx
>    const loginError = useSelector<RootState, RootState["user"]["error"]>(
```suggestion
  const loginError = useSelector<RootState, RootState["user"]["authUser"]["error"]>(
```

2022-09-22 23:37 UTC, Mykyta-Pysarev commented on src/containers/LoginForm.tsx
>      (store) => store.user.error
```suggestion
    (store) => store.user.authUser.error
```

2022-09-22 23:37 UTC, Mykyta-Pysarev commented on src/containers/LoginForm.tsx
>    const loginError = useSelector<RootState, RootState["user"]["error"]>(
After my commit it will not work. I changed structure of user storage.

2022-09-25 13:06 UTC, DavidKorystov approved these changes

2022-09-25 13:39 UTC, VitaliiDenysyuk approved these changes
lgtm

2022-09-25 13:43 UTC, Mykyta-Pysarev approved these changes

2022-09-25 13:49 UTC, alexandrtovmach approved these changes

2022-09-25 13:49 UTC, alexandrtovmach commented on src/containers/Registration.tsx
> +            name="dateOfBirth"
it's coming from your browser settings I believe

2022-09-25 13:49 UTC, merged