Feature/connect tags to trends page
attech-org/leleka pull request #120
Opened 2022-09-25 13:18 UTC by Barylo

![image](https://user-images.githubusercontent.com/89450161/192145401-2eebcd51-e0fd-4d43-b917-faaeb68324b1.png)
Connected Tags to backend + sorting when search and when rendered by a count of the number of tweets.
Tags now are render on Trends page.

2022-09-25 14:09 UTC, alexandrtovmach requested changes

2022-09-25 14:09 UTC, alexandrtovmach commented on src/components/AsyncSearch.tsx
> +        nextPage: undefined,
why do you need this?

2022-09-25 14:09 UTC, alexandrtovmach commented on src/components/AsyncSearch.tsx
> +                  stats={option.tweets}
if I'm not wrong
```suggestion
                  stats={option.stats.tweets}
```

2022-09-25 14:09 UTC, alexandrtovmach commented on src/components/AsyncSearch.tsx
> +                  stats={option.tweets}
replace:
```
typeof option === "object" ? (
// ...
```
with:
```
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const isTag = (data: any): data is Tag => data && typeof data === "object";
// ...
isTag(option) ? (
  <TagItem
    key={option._id}
    _id={option._id}
    name={option.name}
    createdAt={option.createdAt}
    updatedAt={option.updatedAt}
  />
) : (
  <>{option}</>
)
```

2022-09-25 14:19 UTC, ArtemLigerko commented
I think trends has something another functionality, it must shows all tags that often founds in tweets, not only tags what I search. Am I right?

2022-09-25 16:16 UTC, Barylo commented
> I think trends has something another functionality, it must shows all tags that often founds in tweets, not only tags what I search. Am I right?

Yep, you are right. I'll find out how to make it.

2022-09-25 16:34 UTC, Barylo commented on src/components/AsyncSearch.tsx
> +        nextPage: undefined,
This reducer was modified to be reused in two tasks.
The first purpose of it was only to fetch tags for when you search for tags. It wasn't in use of render tags in Trends page. For this purpose, there was only "searchString" parameter. To use this reducer for the fetch and render tags at Trends page I added to is parameters of "limit" and "nextPage" which are not useful for the first purpose.
You can see this reducer at the previous stage in develop and here it's with mine additions.

2022-09-25 16:34 UTC, ArtemLigerko commented
> > I think trends has something another functionality, it must shows all tags that often founds in tweets, not only tags what I search. Am I right?
> 
> Yep, you are right. I'll find out how to make it.

![WM-Screenshots-20220925193315](https://user-images.githubusercontent.com/103952847/192154685-59197726-ce05-4f07-aca8-5adaac98c64c.png)
..like this;

2022-09-25 18:44 UTC, Barylo commented on src/components/AsyncSearch.tsx
> +                  stats={option.tweets}
ts says it should be:
isTag(option) ? (
                <TagItem
                  key={option._id}
                  _id={option._id}
                  name={option.name}
                  createdAt={option.createdAt}
                  updatedAt={option.updatedAt}
                  stats={{
                    tweets: 0,
                  }}
                />

2022-09-25 18:47 UTC, Barylo commented on src/components/AsyncSearch.tsx
> +                  stats={option.tweets}
> const isTag = (data: any): data is Tag => data && typeof data === "object";

with const isTag
ts do not allow  stats={option.stats.tweets}
ts says it should be  stats={option.stats}

without const isTag ts allow  stats={option.stats.tweets}

2022-09-25 18:50 UTC, Barylo commented
> > > I think trends has something another functionality, it must shows all tags that often founds in tweets, not only tags what I search. Am I right?
> > 
> > 
> > Yep, you are right. I'll find out how to make it.
> 
> ![WM-Screenshots-20220925193315](https://user-images.githubusercontent.com/103952847/192154685-59197726-ce05-4f07-aca8-5adaac98c64c.png) ..like this;

When arter you first searched then you see those searched tags during current session, but when refresh it disapears. it should be remembered in storage what have been searched the other session before.

2022-09-25 19:40 UTC, ArtemLigerko commented
> > > > I think trends has something another functionality, it must shows all tags that often founds in tweets, not only tags what I search. Am I right?
> > > 
> > > 
> > > Yep, you are right. I'll find out how to make it.
> > 
> > 
> 
> When arter you first searched then you see those searched tags during current session, but when refresh it disapears. it should be remembered in storage what have been searched the other session before.

You don`t needs search functionality for this, just make request and reply list of trends in "Trends for you" sitebar, use 'tags' reducer and add new actions for this

2022-09-27 12:51 UTC, ArtemLigerko approved these changes

2022-09-27 12:51 UTC, ArtemLigerko commented on src/redux/reducers/tags.ts
> +  searchString: string | undefined;
```suggestion
  limit: number;
  nextPage: number;
  searchString: string;
```

2022-09-27 12:51 UTC, ArtemLigerko commented on src/components/AsyncSearch.tsx
> +        nextPage: undefined,
You can add additional actions for it

2022-09-27 12:51 UTC, ArtemLigerko commented on src/containers/BookmarksList.tsx
> +            "You have not any bookmarks yet. Please add some and you will see them here"
use  i18next

2022-09-27 12:51 UTC, ArtemLigerko commented on src/containers/Trends.tsx
> +    );
you use this block two times. create arrow function and call it.

2022-09-28 03:17 UTC, DavidKorystov approved these changes

2022-09-28 13:33 UTC, KirillSerg approved these changes
lgtm

2022-09-28 13:33 UTC, KirillSerg commented on src/components/TrendItem.tsx
> +        <p className="pb-1 fw-bold">{trend.name}</p>
perhaps it is better not to duplicate the name, but to use the user.name

2022-09-28 17:13 UTC, merged