Feature/connect follow unfollow
attech-org/leleka pull request #130
Opened 2022-09-29 16:00 UTC by ArtemLigerko

2022-09-29 16:07 UTC, DavidKorystov approved these changes
lgtm

2022-09-29 16:07 UTC, DavidKorystov commented on src/redux/reducers/user.ts
> +      store.followedUser.error = "Failed to fetch followimg user";
```suggestion
      store.followedUser.error = "Failed to fetch following user";
```

2022-09-29 16:07 UTC, DavidKorystov commented on src/redux/reducers/user.ts
> +      store.followedUser.error = "Failed to fetch followimg user";
```suggestion
      store.followedUser.error = "Failed to fetch following user";
```

2022-09-29 17:45 UTC, alexandrtovmach requested changes

2022-09-29 17:45 UTC, alexandrtovmach commented on src/containers/Banner.tsx
> +  >((store) => store.user.userByUsername._id);
```
  const currentUser = useSelector<
    RootState,
    RootState["user"]["userByUsername"]
  >((store) => store.user.userByUsername);

// ...

const handleFollowClick = () => {
    if (isFollowed) {
      dispatch(userActions.deleteFollower(currentUser._id));
```

2022-09-29 17:45 UTC, alexandrtovmach commented on src/containers/Banner.tsx
> +  const [isFollowed, setIsFollowed] = useState(user?.isFollowed);
remove this state and use `currentUser.isFollowed`

2022-09-29 17:45 UTC, alexandrtovmach commented on src/containers/Banner.tsx
> +  const handleFollowClick = () => {
`event.preventDefault()` to avoid unnecessary page reload

2022-09-29 17:45 UTC, alexandrtovmach commented on src/redux/reducers/user.ts
> +      store.followedUser = { ...payload };
we don't need to keep this data in store

2022-09-29 17:45 UTC, alexandrtovmach commented on src/containers/Banner.tsx
> +            {buttonText}
add spinner instead of text if `followedUser.isLoading` and disable button to prevent additional press

2022-09-29 18:37 UTC, VitaliiDenysyuk requested changes

2022-09-29 18:37 UTC, VitaliiDenysyuk commented on src/containers/Banner.tsx
> +    if (isFollowed || false) {
```suggestion
    if (isFollowed) {
```
"|| false" nonsence

2022-09-30 16:25 UTC, alexandrtovmach approved these changes

2022-09-30 16:25 UTC, merged