Feat/api service
attech-org/leleka pull request #26
Opened 2022-08-22 21:57 UTC by KirillSerg

- create src/services/api.ts
- install [axios](https://www.npmjs.com/package/axios)
- create instance of axios with base URL that gets from
- research and add interceptors to manage token

2022-08-22 22:12 UTC, Mykyta-Pysarev approved these changes
Looks complicated. Hope it works :)

There is a lot of comments in the code. Do we really need them?

2022-08-23 13:08 UTC, VitaliiDenysyuk requested changes

2022-08-23 13:08 UTC, VitaliiDenysiuk commented on src/services/api.ts
> +  headers: {
- do not save url inside module, we can use different url for production and develop.
move "http://localhost:3001/" in .env
- add .env in .gitignore
- use .env functionality

[examle .env functionality](https://stackoverflow.com/questions/49579028/adding-an-env-file-to-react-project) for this

remove part "/api" from baseURL. Some our url will have not such part

2022-08-23 13:08 UTC, VitaliiDenysyuk commented on src/services/api.ts
> +      }; // for Node.js Express back-end
```suggestion
      if (config.headers) {
        config.headers["x-access-token"] = token; // for Node.js Express back-end
      }
```
better such way

2022-08-23 13:08 UTC, VitaliiDenysyuk commented on src/services/api.ts
> +    if (originalConfig.url !== "/auth/login" && err.response) {
```suggestion
    if (originalConfig.url !== "/api/auth/login" && err.response) {
```

2022-08-23 13:08 UTC, VitaliiDenysyuk commented on src/services/api.ts
> +  return instance.post("/auth/refreshtoken", {
```suggestion
  return instance.post("/api/auth/refreshtoken", {
```

2022-08-23 13:08 UTC, VitaliiDenysyuk commented on src/services/api.ts
> +    const res = await instance.post("/auth/register", {
```suggestion
    const res = await instance.post("/api/auth/register", {
```

2022-08-23 13:08 UTC, VitaliiDenysyuk commented on src/services/api.ts
> +    const res = await instance.get("/testAuthorized");
```suggestion
    const res = await instance.get("/api/testAuthorized");
```

2022-08-23 18:25 UTC, VladislavPokhyl approved these changes

2022-08-23 22:32 UTC, KirillSerg commented on src/services/api.ts
> +  headers: {
thanks for knowledge & link.
Done.

2022-08-23 22:33 UTC, KirillSerg commented on src/services/api.ts
> +      }; // for Node.js Express back-end
thanks. Done

2022-08-23 22:33 UTC, KirillSerg commented on src/services/api.ts
> +    if (originalConfig.url !== "/auth/login" && err.response) {
done

2022-08-23 22:33 UTC, KirillSerg commented on src/services/api.ts
> +  return instance.post("/auth/refreshtoken", {
done

2022-08-23 22:33 UTC, KirillSerg commented on src/services/api.ts
> +    const res = await instance.post("/auth/register", {
done

2022-08-23 22:33 UTC, KirillSerg commented on src/services/api.ts
> +    const res = await instance.get("/testAuthorized");
done

2022-08-24 09:41 UTC, VitaliiDenysyuk submitted a review, later dismissed
looks good to me

2022-08-24 10:00 UTC, VitaliiDenysyuk approved these changes
looks good to me

2022-08-24 16:01 UTC, alexandrtovmach requested changes
looks good but not ideal
the current flow refreshing token after failed attempt to get required data, but how about to avoid unnecessary request? You can parse token on frontend side before sending original request to check if it's fresh. Refresh token if it's not fresh and send original request if everything fine.

2022-08-26 08:05 UTC, alexandrtovmach approved these changes

2022-08-26 08:06 UTC, merged