feat/added link preview component
attech-org/leleka pull request #31
Opened 2022-08-24 15:35 UTC by DavidKorystov

```
<LinkPreview url={"https://getbootstrap.com/docs/5.0/components/card/"} />
```

2022-08-24 15:43 UTC, VladislavPokhyl approved these changes

2022-08-24 16:05 UTC, Mykyta-Pysarev approved these changes
Looks good to me

2022-08-24 16:47 UTC, alexandrtovmach requested changes
few changes please

2022-08-24 16:47 UTC, alexandrtovmach commented on src/components/LinkPreview.tsx
> +  width: 300px;
why magic 300px?

2022-08-24 16:47 UTC, alexandrtovmach commented on src/components/LinkPreview.tsx
> +  width: 300px;
this component will be used inside another components, so it shouldn't shouldn't have limited width

2022-08-24 16:47 UTC, alexandrtovmach commented on src/components/LinkPreview.tsx
> +    fetch("https://api.linkpreview.net", {
move this logic to separate service "services/linkPreview.ts"

2022-08-24 16:47 UTC, alexandrtovmach commented on src/components/LinkPreview.tsx
> +      <div className="card-body ">
use react-bootstrap analouge conmponents instead of pure classes

2022-08-25 07:33 UTC, ArtemLigerko commented on src/components/LinkPreview.tsx
> +          // console.log(res.status);
please, remove comment

2022-08-25 09:42 UTC, ArtemLigerko approved these changes

2022-08-26 08:05 UTC, alexandrtovmach approved these changes

2022-08-26 08:05 UTC, merged