feat/replaced services/preview on customFether
attech-org/leleka pull request #39
Opened 2022-08-26 17:51 UTC by DavidKorystov

Example:

```
<LinkPreview url="https://www.youtube.com/watch?v=jfKfPfyJRdk" />
```

![image](https://user-images.githubusercontent.com/94183891/186963128-ae35a841-d2e5-4cee-b7c0-0695b6d16cfe.png)

2022-08-26 19:37 UTC, KirillSerg commented on src/services/customFetcher.ts
> +  // console.warn(json.metadata);
you need it console? ))

2022-08-26 19:38 UTC, KirillSerg approved these changes
+

2022-08-28 11:33 UTC, ArtemLigerko commented
did you looks for another link preview services, for example https://www.peekalink.io/. It provides more aditional fields in free plan. Should you check it?

2022-08-28 13:30 UTC, alexandrtovmach requested changes

2022-08-28 13:30 UTC, alexandrtovmach commented on src/services/customFetcher.ts
> +    `http://127.0.0.1:3001/api/link-preview/?url=${url}`
```suggestion
    `${process.env.REACT_APP_SERVER_URL}/api/link-preview/?url=${url}`
```

2022-08-28 13:30 UTC, alexandrtovmach commented on src/components/LinkPreview.tsx
> +    customFetcher(url).then((res) => {
rewrite Promise then with async/await

2022-08-28 13:30 UTC, alexandrtovmach commented on src/components/LinkPreview.tsx
> +        res.image = "https://" + res.hostname + res.image;
```suggestion
        res.image = `https://${res.hostname}${res.image}`
```

2022-08-28 13:30 UTC, alexandrtovmach commented on src/components/LinkPreview.tsx
> +      if (res.image[0] !== "h") {
```suggestion
      if (!res.image.startsWith("http")) {
```

2022-08-28 13:31 UTC, alexandrtovmach commented on src/components/LinkPreview.tsx
> +        res.image = "https://" + res.hostname + res.image;
this should be moved to backend

2022-08-28 13:31 UTC, alexandrtovmach commented on src/components/LinkPreview.tsx
> +      if (res.image[0] !== "h") {
this should be moved to backend

2022-08-29 14:09 UTC, VitaliiDenysyuk requested changes

2022-08-29 14:09 UTC, VitaliiDenysiuk commented on src/components/LinkPreview.tsx
> +    };
move the description of this "getResponse" function out of the useEffect block.

Perhaps it will be useful elsewhere later.

2022-08-29 16:10 UTC, VitaliiDenysyuk requested changes

2022-08-29 16:10 UTC, VitaliiDenysyuk commented on src/components/LinkPreview.tsx
> +          {response.siteName !== "" && response.hostname !== "" && (
```suggestion
          {response.siteName  && response.hostname && (
```

2022-08-29 16:46 UTC, VitaliiDenysyuk approved these changes
looks good to me

2022-08-31 14:40 UTC, vasyagladush approved these changes

2022-08-31 16:23 UTC, alexandrtovmach approved these changes

2022-08-31 16:23 UTC, merged