added Reacr-dev-tools V3
attech-org/leleka pull request #4
Opened 2022-08-12 14:50 UTC by timurkinsan

Added dev-tools to Project  Leleka

2022-08-12 16:10 UTC, alexandrtovmach requested changes
I can't find changes in package.json with installed redux-dev-tools package

2022-08-12 16:10 UTC, alexandrtovmach commented on src/redux/store.ts
> +   */
remove this useless comment

2022-08-14 14:01 UTC, alexandrtovmach approved these changes

2022-08-14 20:12 UTC, timurkinsan reviewed
Allowed to merge conflicts

2022-08-14 23:46 UTC, alexandrtovmach approved these changes

2022-08-14 23:46 UTC, merged