connect followers pages with profile page
attech-org/leleka pull request #50
Opened 2022-09-01 21:32 UTC by Tretmax

![image](https://user-images.githubusercontent.com/103947044/188016705-eb270ec4-22ac-4ea4-b438-5640dccaff5e.png)
create links on followers

2022-09-02 07:55 UTC, Mykyta-Pysarev approved these changes
Looks good.

2022-09-02 13:00 UTC, ArtemLigerko commented
Nice! And can you add cursor pointer to 'following' and 'followers' links

2022-09-02 16:16 UTC, Tretmax commented
> 

done

2022-09-02 16:37 UTC, alexandrtovmach requested changes

2022-09-02 16:37 UTC, alexandrtovmach commented on src/pages/Profile.tsx
> +          <UnderlineHover
why not to use link?

2022-09-05 10:52 UTC, ArtemLigerko approved these changes

2022-09-05 16:03 UTC, alexandrtovmach approved these changes

2022-09-05 16:04 UTC, merged