Feature/create single tweet component
attech-org/leleka pull request #7
Opened 2022-08-15 17:09 UTC by ArtemLigerko

2022-08-16 07:45 UTC, Mykyta-Pysarev commented on src/components/SingleTweet.tsx
> +`;
You could use one styled component with props for Icon, IconBg etc.

2022-08-16 07:45 UTC, Mykyta-Pysarev approved these changes
Overall seems ok.

2022-08-16 16:27 UTC, ArtemLigerko commented
![image](https://user-images.githubusercontent.com/103952847/184930678-2ab7b2d5-37c6-4c3e-9103-6f5dc61d3133.png)

2022-08-16 16:42 UTC, KirillSerg approved these changes

2022-08-16 16:42 UTC, KirillSerg commented on package.json
> +    "react-bootstrap-icons": "^1.8.4",
it will be on my merg

2022-08-16 16:42 UTC, KirillSerg commented on package.json
> +    "react-icons": "^4.4.0",
are they really needed?

2022-08-16 19:34 UTC, Tretmax commented on src/components/SingleTweet.tsx
> +const Name = styled.div`
maybe UserName

2022-08-16 20:45 UTC, alexandrtovmach requested changes
remove bootstrap.min.css from components folder

2022-08-16 20:45 UTC, alexandrtovmach commented on package.json
> +    "react-icons": "^4.4.0",
also interested

2022-08-16 20:45 UTC, alexandrtovmach commented on src/components/SingleTweet.tsx
> +  padding: 0 16px;
margins and paddings in bootstrap can be managed in next way:
https://getbootstrap.com/docs/4.0/utilities/spacing/

please fix here and everywhere

2022-08-16 20:45 UTC, alexandrtovmach commented on src/components/SingleTweet.tsx
> +  max-width: 598px;
what's a magic number?

2022-08-16 20:45 UTC, alexandrtovmach commented on src/components/SingleTweet.tsx
> +const Name = styled.div`
Username, without upper N

2022-08-16 20:45 UTC, alexandrtovmach commented on src/components/SingleTweet.tsx
> +  font-weight: bold;
font customization can be solved with bootstrap Text modifications
https://getbootstrap.com/docs/4.0/utilities/text/#font-weight-and-italics

fix here and everywhere

2022-08-16 20:45 UTC, alexandrtovmach commented on src/components/SingleTweet.tsx
> +                </svg>
I thought we agreed to use icons instead of SVG?

2022-08-16 20:45 UTC, alexandrtovmach commented on src/components/bootstrap.min.css
> +@charset "UTF-8"; /*!
what a hell is that?

2022-08-16 21:09 UTC, ArtemLigerko commented on src/components/SingleTweet.tsx
> +  max-width: 598px;
like in Tweeter

2022-08-16 21:11 UTC, ArtemLigerko commented on src/components/bootstrap.min.css
> +@charset "UTF-8"; /*!
fogot delete it

2022-08-17 19:59 UTC, alexandrtovmach approved these changes

2022-08-17 19:59 UTC, alexandrtovmach commented on public/index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorig
delete that

2022-08-17 19:59 UTC, alexandrtovmach commented on public/index.html
> +    <!-- CSS only -->
```suggestion
```

2022-08-17 19:59 UTC, merged