Feature/tweet component fetch
attech-org/leleka pull request #78
Opened 2022-09-11 16:46 UTC by Mykyta-Pysarev

![image](https://user-images.githubusercontent.com/103769012/189539297-e6bce935-01a7-4209-824c-0039e371af32.png)

Now tweet opens with comments if you click on the date.

2022-09-11 19:07 UTC, VladislavPokhyl approved these changes

2022-09-12 08:43 UTC, KirillSerg commented on src/containers/ProfileTweets.tsx
> +      {/* {mockUsers && (
You don't rener it? And don't use the approach from similar components.

2022-09-12 08:44 UTC, KirillSerg commented on src/containers/TweetPage.tsx
> +        {/* <SingleTweet {...singleTweetData} /> */}
What differents?

2022-09-12 08:58 UTC, KirillSerg commented on src/components/FeedSingleTweet.tsx
> +              <UnderlineHover
Did I understand correctly that when clicking on the date of creation, it redirects to a page with a specific tweet (by id)? Then why only when clicking on the date and not the entire tweet (the entire tweet field)

2022-09-12 09:05 UTC, KirillSerg commented on src/containers/TweetsWithReplies.tsx
> +  );
can we use specific tweets already as below
const posts = useSelector<RootState, RootState["tweets"]["feedReplies"]>(
    (store) => store.tweets.feedReplies
  );

2022-09-12 12:30 UTC, VitaliiDenysiuk requested changes

2022-09-12 12:30 UTC, VitaliiDenysiuk commented on src/components/SingleTweet.tsx
> +// import AttachedContent from "./AttachedContent";
```suggestion
// import AttachedContent from "./AttachedContent";
```
clean code

2022-09-12 12:30 UTC, VitaliiDenysiuk commented on src/components/SingleTweet.tsx
> +  // updatedAt,
```suggestion
  author,
  content,
  createdAt,
  updatedAt,
```
clean code
use updatedAt on form

2022-09-12 12:30 UTC, VitaliiDenysiuk commented on src/components/SingleTweet.tsx
> +          {createdAt} - "lelekaLink"
use normal data format (dd.mm.yyyy hh:mm) 
maybe it's needded add updatedAt to

2022-09-12 12:30 UTC, VitaliiDenysiuk commented on src/containers/ProfileLikes.tsx
> +    return !posts.isLoading && dispatch(tweetsActions.fetchFeedTweets(posts));
```suggestion
    return !posts.isLoading && posts.hasNextPage && dispatch(tweetsActions.fetchFeedTweets(posts));
```

2022-09-12 12:30 UTC, VitaliiDenysiuk commented on src/containers/ProfileMedia.tsx
> +    return !posts.isLoading && dispatch(tweetsActions.fetchFeedTweets(posts));
```suggestion
    return !posts.isLoading && posts.hasNextPage && dispatch(tweetsActions.fetchFeedTweets(posts));
```

2022-09-12 12:30 UTC, VitaliiDenysiuk commented on src/containers/ProfileTweets.tsx
> +// import SingleTweet from "../components/SingleTweet";
```suggestion

```
clean

2022-09-12 12:30 UTC, VitaliiDenysiuk commented on src/containers/ProfileTweets.tsx
> +// import InfiniteList from "./InfiniteList";
```suggestion

```
clean

2022-09-12 12:30 UTC, VitaliiDenysyuk commented on src/containers/ProfileTweets.tsx
> +      )} */}
clean

2022-09-12 12:30 UTC, VitaliiDenysyuk commented on src/containers/TweetPage.tsx
> +// import { singleTweetData } from "../MOCKS/singleTweetPage";
```suggestion

```
clean

2022-09-12 12:30 UTC, VitaliiDenysyuk commented on src/containers/TweetsWithReplies.tsx
> +    return !posts.isLoading && dispatch(tweetsActions.fetchFeedTweets(posts));
```suggestion
    return !posts.isLoading && posts.hasNextPage && dispatch(tweetsActions.fetchFeedTweets(posts));
```

2022-09-12 18:11 UTC, alexandrtovmach requested changes
small changes only

2022-09-12 18:11 UTC, alexandrtovmach commented on src/redux/reducers/tweets.ts
> +  feedReplies: LE<Pagination<Tweet2>>;
```suggestion
  currentTweetRelies: LE<Pagination<Tweet2>>;
```

2022-09-13 07:44 UTC, alexandrtovmach requested changes

2022-09-13 07:44 UTC, alexandrtovmach commented on src/redux/reducers/tweets.ts
> +  currentTweetRelies: LE<Pagination<Tweet2>>;
```suggestion
  currentTweetReplies: LE<Pagination<Tweet2>>;
```

2022-09-13 07:58 UTC, alexandrtovmach approved these changes

2022-09-13 07:59 UTC, merged